name: srhqwebsite
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  dynamic_color: ^1.6.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^6.0.1
  hooks_riverpod: ^2.1.3
  lottie: ^2.2.0
  riverpod: ^2.1.3

  srhqdesignpackage:
    git:
      url: https://github.com/SRHQNepal/srhqdesignpackage.git
      ref: main ## branch name for design package

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
